version: '3.7'

services:
  build_app:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - type: volume
        source: app
        target: /home/target
  webapp:
    image: tomcat:8.0-alpine
    ports:
      - "80:8080"
    volumes:
      - type: volume
        source: app
        target: /usr/local/tomcat/webapps
volumes:
  app: