---
version: '3.7'

services:
  webapp:
    image: davidcaste/docker-alpine-tomcat:jdk7tomcat7
    ports:
      - "80:8080"
    volumes:
      - type: volume
        source: app
        target: /opt/tomcat/webapps

  build_app:
    build:
      dockerfile: Dockerfile
    volumes:
      - type: volume
        source: app
        target: /home/boxfuse-sample-java-war-hello/target

volumes:
  app: