version: '3.7'

services:
  build_app:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./app:/home/target
  webapp:
    image: tomcat:8.0-alpine
    ports:
      - "80:8080"
    volumes:
      - ./app:/usr/local/tomcat/webapps
volumes:
  app: