version: '3.7'

services:
  webapp:
    image: tomcat:8.0-alpine
    container_name: web_app
    ports:
      - "80:8080"
    volumes:
      - type: volume
        source: ./app/
        target: /usr/local/tomcat/webapps/

  build_app:
    build:
      container_name: build_app
      context: ./
      dockerfile: Dockerfile
    volumes:
      - type: volume
        source: ./app/
        target: /home/target/

#volumes:
#  app: